### ISSUE TITLE
test_threads_posting_large_messages_do_not_starve is flaky

### ISSUE THREAD

**Issue by pradn** [googleapis/python-pubsub#179] opened 2020-08-27 21:43 UTC
Traceback (most recent call last):
  File "/build/work/3e717c5f26b97eb536d86b319348564b6054/google3/runfiles/google3/third_party/py/google/cloud/pubsub/tests/unit/pubsub_v1/publisher/test_flow_controller.py", line 333, in test_threads_posting_large_messages_do_not_starve
    pytest.fail("Releasing messages blocked or errored.")
  File "/build/work/3e717c5f26b97eb536d86b319348564b6054/google3/runfiles/google3/third_party/py/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Releasing messages blocked or errored.

**Comment by plamut** [comment] 2020-09-10 14:31
@pradn How often can you reproduce the failure? Is this locally or was observed on Kokoro, too?

**Comment by HemangChothani** [comment] 2020-09-17 13:42
@pradn @plamut I have also tried plenty of times locally, but it doesn't failed.

**Comment by meredithslota** [comment] 2020-10-15 17:40
Unable to repro, closing. Please reopen if this happens again. :)

**Comment by pradn** [comment] 2020-10-30 23:43
I can consistently repro this. In 10,000 runs, it failed with this error in 173 runs (python3). It's less often in python2.

**Comment by mukund-ananthu** [comment] 2024-11-02 21:55
Closing this since this test hasn't been observed to fail for quite some time now(since 2020).

**Closed by mukund-ananthu** 2024-11-02 21:55 UTC
Labels: api: pubsub, type: process, testing
