### ISSUE TITLE
Pubsub client is not correctly acknowledging the messages when sending acks in batches

### ISSUE THREAD

**Issue by immohsin** [googleapis/python-pubsub#73] opened 2020-04-15 16:12 UTC
Google Cloud service stack I use is  Bigquery, Cloud Function, Pubsub and Cloud Scheduler. I try to process all messages in pubsub using Cloud Function and ingest them to Bigquery all at once at the end of subscription timeout and if all went good I send the acknowledgement. But in recent days, The number of messages on pubsub is growing and I have increased the frequency of cloud function scheduling and implemented sending data in batch to Bigquery since the bigquery python client has a limit on bytes you can send at once. It works good and inserts the data in Bigquery But when it comes to sending acks almost half of the messages are not getting correctly acknowledged and sometimes no messages get acknowledged. My pubsub ack deadline is 600 seconds. 

#### Environment details
I'm working on my system with below configuration.

  - OS type and version: macOS High Sierra
  - Python version: `Python 3.6.5`
  - pip version: `pip 20.0.2`
  - `google-cloud-pubsub` version: `1.1.0`

#### Steps to reproduce

  1. Insert the data to Bigquery in batch
  2. Send acks to only those messages which got inserted in the batch

#### Code example
Code Sample

```python
SUBSCRIPTION_TIMEOUT = 420.0

def ingest_to_bq(data, acks, valid_data):
    table = TABLE if valid_data else INVALID_TABLE
    start, end = 0, EVENT_CHUNK_SIZE
    data_len = len(data)
    print("Total data size:", data_len)
    while(start < data_len):
        chunked_data = data[start:end]
        chunked_ack_ids = acks[start:end]
        errors = bigquery_client.insert_rows(table, chunked_data)
        if len(errors):
            print("Error inserting app events to bigquery", file=sys.stderr)
            break
        else:
            print("Successfully inserted {count} app events data to bigquery".format(  # noqa
                count=len(chunked_data))
            )
            pubsub_client.acknowledge(subscription_path, chunked_ack_ids)
            start += EVENT_CHUNK_SIZE
            end += EVENT_CHUNK_SIZE

def bq_ingestion_process(valid_data=True):
    data = MESSAGE_LIST if valid_data else INVALID_MESSAGE_LIST
    ack_ids = MESSAGE_ACK_LIST if valid_data else INVALID_MESSAGE_ACK_LIST
    ingest_to_bq(data, ack_ids, valid_data)

def main(request):
    streaming_pull_future = pubsub_client.subscribe(
        subscription_path, callback=streaming_subscriber_callback
    )

    print("Listening for messages on {}...".format(subscription_path))

    try:
        streaming_pull_future.result(timeout=SUBSCRIPTION_TIMEOUT)
    except Exception:
        streaming_pull_future.cancel()
    finally:
        # ingest entire data to bigquery after timeout.
        if MESSAGE_ACK_LIST:
            bq_ingestion_process()
        if INVALID_MESSAGE_ACK_LIST:
            bq_ingestion_process(valid_data=False)
```

Thanks!

**Comment by plamut** [comment] 2020-04-16 15:18
@immohsin Are all messages published to the topic actually dispatched to the `streaming_subscriber_callback()` and then inserted into BigQuery? And no errors occur during the process?

Asking because the `except Exception` line can catch a broad range of errors, not just the `TimeoutError` raised by the future.

Another question is how many messages does the app typically receive? Is it possible that you are hitting `types.FlowControl` limits and not all messages are dispatched to the callback? Asking because it appears that the `ingest_to_bq()` function is the first place where messages get acknowledged.

If there are too many outstanding messages (i.e. received, but not yet acknowledged), the message stream gets paused until some of the messages have been acknowledged. Also mind that when using the streaming pull, the messages should be acknowledged by calling their `.ack()` method, not by manually using the client's `acknowledge()` method.

Doing `message.ack()` assures that these messages are automatically released from the internal lease management, freeing up the capacity to dispatch more message to the subscription callback.

These would be the things that I would check first.

**Comment by immohsin** [comment] 2020-04-16 15:51
Hi @plamut, Thank you for replying.

1. Yes, all the messages pushed to the topic is getting inserted into BIgquery. No issue with that.

2. Not too many messages. Tried with as low as 80 messages and a batch size of 5(just for testing), the acknowledgement is not received correctly for more than 8 messages.

3.  If outstanding messages is the problem, then how does it impact acknowledging already received messages.  Does it mean the client's `acknowledge()` method is error-prone? If that's the case then maybe I need to rethink on how to send sacks correctly.

**Comment by pradn** [comment] 2020-04-16 18:30
You should use the message.ack() method, as Peter mentioned. Make sure to call close() on the subscriber or wrap it in a 'with' block to ensure the underlying socket is closed in an orderly way. ([See example](https://cloud.google.com/pubsub/docs/pull#asynchronous-pull).)

Acks are best-effort, and missed acks are one reason why you might see duplicates on pull. What is the % of "missed acks" you are seeing?

I wonder if there's an issue with how the subscriber client is torn down in Cloud Functions. The library was designed more for long-running server processes.

**Comment by yiga2** [comment] 2020-04-16 21:46
Why receiving in batch ? Typically you would use a cloud function as a push subscription, and insert one row/message at a time. Being atomic, timeout is impossible and you can better troubleshoot what went wrong e.g. message or row size too large (in which case we save to GCS).

**Comment by pradn** [comment] 2020-04-16 22:00
It's likely immohsin is batching writes to BQ to save Cloud Function invocation costs.

**Comment by immohsin** [comment] 2020-04-17 04:44
@pradn Giving % of missed acks is tough as I have seen many messages missing acks sometimes. 

Maybe its time to insert one row at a time and send ack by message.ack() method.

I was not using the client in `With` block earlier but I have changed now. I guess the client should now gracefully teardown. Is there something more to it?

**Comment by plamut** [comment] 2020-04-17 10:02
@immohsin 

> Can you please explain why message.acks() method is better than client's acknowledge() method?

When using the streaming pull (the `subscriber.subscribe()` method), all received messages are automatically lease-managed, meaning that their ACK deadlines automatically get extended regularly until the client is done processing them.

The number of messages under lease management also affects the client load factor, and if the load is too high, the message stream is paused to not flood the client if it needs more time to process the messages.

Now, when a message is acknowledged through its `ack()` method, this action is asynchronously processed in the [background](https://github.com/googleapis/python-pubsub/blob/1775636693d2678a3e3674215c247b493185e1e7/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py#L125-L160). Besides acknowledging it, the message is also dropped from the lease management, opening up the capacity for more messages.

Acknowledging such messages manually with the `client.acknowledge()` method bypasses this mechanism, and while the message does get acknowledged on the backend, the client is not aware of that and might unnecessarily keep the message stream paused if overloaded.

> I was not using the client in With block earlier but I have changed now. I guess the client should now gracefully teardown. Is there something more to it?

That should be it. Using the subscriber client in a `with` block assures that its `close()` method is called when exiting the block, which closes the underlying transport channel and prevents leaking the sockets.

**Comment by plamut** [comment] 2020-04-17 10:24
@immohsin Thinking through this more - you mention that your ACK timeout is 600 seconds, but that value is not necessarily fixed.

When the stream is initially created, the default ACK deadline is [modified](https://github.com/googleapis/python-pubsub/blob/1775636693d2678a3e3674215c247b493185e1e7/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L449-L461). The exact deadline value depends on the ACK times history, but initially when there is no data, the deadline defaults to [10 seconds](https://github.com/googleapis/python-pubsub/blob/1775636693d2678a3e3674215c247b493185e1e7/google/cloud/pubsub_v1/subscriber/_protocol/histogram.py#L127-L154).

The ACK deadline then gets regularly extended until a message is processed, however, if the code shuts down the stream (by canceling the streaming pull future), the ACK deadlines are not being extended anymore. If the post-processing (inserting the data into BigQuery) takes some time, it might result in some of the messages already expiring before the ACK is finally sent. This might explain the unusually high number of unacknowledged messages.

The fix would be to either somehow process the messages before the future is canceled, or manually extend the ACK deadlines after canceling it with `subscriber.modify_ack_deadline()` (although that kind of manual work somewhat beats the purpose of the automatic streaming).

**Comment by immohsin** [comment] 2020-04-17 19:21
Thank you @plamut ,  I have implemented the `subscriber.modify_ack_deadline()` method with proper client teardown and looks like it is working as expected. But I would consider changing the logic of processing and acknowledging a message.

**Comment by yiga2** [comment] 2020-04-17 20:36
@immohsin I understand the saving on GCF invocations and processing cost but make sure it's not marginal as one batch could stay unacked if just one row fails. Also, if you were to consider one per row, the acknowledgement is implicit if function does not error out.

**Comment by immohsin** [comment] 2020-04-18 05:40
@yiga2 Yes, I understand the risk here. While I have implemented a short term solution to test out the business need, I have been thinking through this and I guess I'll have to go with `DataFlow` way to get data from pubsub to Bigquery and that approach is viable to the business in the future.

**Comment by yiga2** [comment] 2020-04-18 22:04
@immohsin out of topic but good luck with dataflow vs. GCF. We have moved away from it for all reasons: cost, performance and features.

**Comment by immohsin** [comment] 2020-04-19 04:49
@yiga2 Moved away from dataflow? If yes, I would love to talk about your current solution and how is it helping. That would be really helpful to me. Thanks!

**Comment by plamut** [comment] 2020-04-20 07:40
@immohsin I'm glad to hear that the solution worked!

Since it turned out that it was not an issue with acknowledging by the client per se, I'm closing this, but feel free to come back it if you encounter new ACK-related problems.

**Closed by plamut** 2020-04-20 07:40 UTC
Labels: api: pubsub, type: question
