### ISSUE TITLE
'ProtoType' object has no attribute 'DESCRIPTOR'

### ISSUE THREAD

**Issue by redvg** [googleapis/python-pubsub#705] opened 2022-06-04 14:22 UTC
constructing PubsubMessage fails with an exception from proto, this may well be related to https://github.com/protocolbuffers/protobuf/issues/10051 tho it would still be great to have some fix

#### Environment details

  - OS type and version:
  - Python version: CPython 3.8.5
  - pip version: 22.1.2
  - `google-cloud-pubsub` version: 2.2.0

#### Steps to reproduce

trying to marshall any kind of payload fails

#### Code example

```python
from cloudevents.http.event import CloudEvent
from cloudevents.http.http_methods import to_binary
from google.pubsub_v1.types.pubsub import PubsubMessage

event: CloudEvent = CloudEvent(context_attributes, event_data)
attr, data = to_binary(event)
message: PubsubMessage = PubsubMessage(
                attributes=attr,
                data=data,
)
```

#### Stack trace
```
AttributeError: 'ProtoType' object has no attribute 'DESCRIPTOR'
  File "brokers/mq.py", line 34, in do
    message: PubsubMessage = PubsubMessage(
  File "proto/message.py", line 561, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "proto/marshal/marshal.py", line 203, in to_proto
    proto_type.DESCRIPTOR.has_options
```

<img width="1088" alt="изображение" src="https://user-images.githubusercontent.com/38582053/172006248-f5917cf0-0547-4920-ad27-c6c9ce054eff.png">

#### deps
```


anyio | 3.6.1
-- | --
asgiref | 3.5.2
astroid | 2.4.2
autopep8 | 1.6.0
cachecontrol | 0.12.11
cachetools | 4.2.4
certifi | 2022.5.18.1
cffi | 1.15.0
charset-normalizer | 2.0.12
click | 8.1.3
cloudevents | 1.2.0
cryptography | 37.0.2
deprecated | 1.2.13
deprecation | 2.1.0
dnspython | 2.2.1
email-validator | 1.2.1
fastapi | 0.78.0
firebase-admin | 5.2.0
flake8 | 3.8.4
gcloud | 0.18.3
google-api-core | 1.27.0
google-api-python-client | 2.39.0
google-auth | 1.24.0
google-auth-httplib2 | 0.1.0
google-cloud-core | 2.2.2
google-cloud-firestore | 2.3.4
google-cloud-pubsub | 2.2.0
google-cloud-storage | 1.41.1
google-crc32c | 1.3.0
google-resumable-media | 2.3.3
googleapis-common-protos | 1.56.2
greenlet | 1.1.2
grpc-google-iam-v1 | 0.12.4
grpcio | 1.34.0
grpcio-status | 1.46.3
h11 | 0.12.0
httpcore | 0.15.0
httplib2 | 0.20.4
httpx | 0.23.0
idna | 3.3
isort | 5.7.0
jwcrypto | 1.3.1
lazy-object-proxy | 1.4.3
libcst | 0.4.3
mccabe | 0.6.1
msgpack | 1.0.4
mypy-extensions | 0.4.3
oauth2client | 4.1.3
packaging | 21.3
pip | 22.1.2
proto-plus | 1.20.5
protobuf | 3.20.0
psycopg2-binary | 2.9.3
pyasn1 | 0.4.8
pyasn1-modules | 0.2.8
pycodestyle | 2.8.0
pycparser | 2.21
pycryptodome | 3.14.1
pydantic | 1.9.1
pyflakes | 2.2.0
pyjwt | 2.4.0
pylint | 2.6.0
pyparsing | 3.0.9
pyrebase4 | 4.5.0
python-dotenv | 0.20.0
python-jwt | 3.3.2
pytz | 2022.1
pyyaml | 6.0
requests | 2.27.1
requests-toolbelt | 0.9.1
rfc3986 | 1.5.0
rsa | 4.8
sentry-sdk | 1.5.12
setuptools | 47.1.0
six | 1.15.0
sniffio | 1.2.0
sqlalchemy | 1.4.36
sqlalchemy-cockroachdb | 1.4.3
starlette | 0.19.1
toml | 0.10.2
typing-extensions | 4.2.0
typing-inspect | 0.7.1
uritemplate | 4.1.1
urllib3 | 1.26.9
uvicorn | 0.17.6
wrapt | 1.12.1


```

**Comment by acocuzzo** [comment] 2022-06-09 14:56
Hi @redvg Thanks for the detailed information. Can you please try updating to 2.13 and see if this fixes your issue?

**Comment by redvg** [comment] 2022-06-23 22:32
hi @acocuzzo  unfortunately this does not fix the issue, here is updated deps: 

google-cloud-pubsub is 2.13.0 instead of 2.2.0




anyio | 3.6.1
-- | --
asgiref | 3.5.2
cachecontrol | 0.12.11
cachetools | 5.2.0
certifi | 2022.6.15
cffi | 1.15.0
charset-normalizer | 2.0.12
click | 8.1.3
cloudevents | 1.2.0
cryptography | 37.0.2
deprecated | 1.2.13
deprecation | 2.1.0
dnspython | 2.2.1
email-validator | 1.2.1
fastapi | 0.78.0
firebase-admin | 5.2.0
gcloud | 0.18.3
google-api-core | 2.8.2
google-api-python-client | 2.51.0
google-auth | 2.8.0
google-auth-httplib2 | 0.1.0
google-cloud-core | 2.3.1
google-cloud-firestore | 2.5.3
google-cloud-pubsub | 2.13.0
google-cloud-storage | 2.4.0
google-crc32c | 1.3.0
google-resumable-media | 2.3.3
googleapis-common-protos | 1.56.3
greenlet | 1.1.2
grpc-google-iam-v1 | 0.12.4
grpcio | 1.47.0
grpcio-status | 1.47.0
h11 | 0.12.0
httpcore | 0.15.0
httplib2 | 0.20.4
httpx | 0.23.0
idna | 3.3
jwcrypto | 1.3.1
msgpack | 1.0.4
oauth2client | 4.1.3
packaging | 21.3
pip | 22.0.4
proto-plus | 1.20.6
protobuf | 3.20.0
psycopg2-binary | 2.9.3
pyasn1 | 0.4.8
pyasn1-modules | 0.2.8
pycparser | 2.21
pycryptodome | 3.15.0
pydantic | 1.9.1
pyjwt | 2.4.0
pyparsing | 3.0.9
pyrebase4 | 4.5.0
python-dotenv | 0.20.0
python-jwt | 3.3.2
requests | 2.28.0
requests-toolbelt | 0.9.1
rfc3986 | 1.5.0
rsa | 4.8
sentry-sdk | 1.5.12
setuptools | 58.1.0
six | 1.16.0
sniffio | 1.2.0
sqlalchemy | 1.4.36
sqlalchemy-cockroachdb | 1.4.3
starlette | 0.19.1
typing-extensions | 4.2.0
uritemplate | 4.1.1
urllib3 | 1.26.9
uvicorn | 0.17.6
wheel | 0.37.1
wrapt | 1.14.1

**Comment by salikadave** [comment] 2022-06-24 07:56
@redvg Did you find a any fix around this? I am facing the same issue

The error says to try downgrading protobuf

`Downgrade the protobuf package to 3.20.x or lower`

Have you found any stable version that helps?

**Comment by acocuzzo** [comment] 2022-07-23 20:03
@redvg I'm sorry I'm not able to reproduce your issue, I am running the following:
```
from cloudevents.http.event import CloudEvent
from cloudevents.http.http_methods import to_binary
from google.pubsub_v1.types.pubsub import PubsubMessage

context_attributes = {
        "type": "com.example.sampletype1",
        "source": "https://example.com/event-producer",
    }
event_data = {"message": "Hello World!"}
event: CloudEvent = CloudEvent(context_attributes, event_data)
attr, data = to_binary(event)
message: PubsubMessage = PubsubMessage(
                attributes=attr,
                data=data,
)

print(message)
```
which outputs the following:
```
data: "{\"message\": \"Hello World!\"}"
attributes {
  key: "ce-id"
  value: "854d6483-daea-4f84-9d40-a4c183e1a43c"
}
attributes {
  key: "ce-source"
  value: "https://example.com/event-producer"
}
attributes {
  key: "ce-specversion"
  value: "1.0"
}
attributes {
  key: "ce-time"
  value: "2022-07-23T19:59:28.119164+00:00"
}
attributes {
  key: "ce-type"
  value: "com.example.sampletype1"
}
```
my pip-freeze:
```
anyio==3.6.1
asgiref==3.5.2
CacheControl==0.12.11
cachetools==5.2.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.0.12
click==8.1.3
cloudevents==1.2.0
cryptography==37.0.2
Deprecated==1.2.13
deprecation==2.1.0
dnspython==2.2.1
email-validator==1.2.1
fastapi==0.78.0
firebase-admin==5.2.0
gcloud==0.18.3
google-api-core==2.8.2
google-api-python-client==2.51.0
google-auth==2.8.0
google-auth-httplib2==0.1.0
google-cloud-core==2.3.1
google-cloud-firestore==2.5.3
google-cloud-pubsub==2.13.0
google-cloud-storage==2.4.0
google-crc32c==1.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.3
greenlet==1.1.2
grpc-google-iam-v1==0.12.4
grpcio==1.47.0
grpcio-status==1.47.0
h11==0.12.0
httpcore==0.15.0
httplib2==0.20.4
httpx==0.23.0
idna==3.3
jwcrypto==1.3.1
msgpack==1.0.4
oauth2client==4.1.3
packaging==21.3
proto-plus==1.20.6
protobuf==3.20.0
psycopg2-binary==2.9.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodome==3.15.0
pydantic==1.9.1
PyJWT==2.4.0
pyparsing==3.0.9
Pyrebase4==4.5.0
python-dotenv==0.20.0
python-jwt==3.3.2
requests==2.28.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
rsa==4.8
sentry-sdk==1.5.12
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.36
sqlalchemy-cockroachdb==1.4.3
starlette==0.19.1
typing_extensions==4.2.0
uritemplate==4.1.1
urllib3==1.26.9
uvicorn==0.17.6
wrapt==1.14.1
```

**Comment by redvg** [comment] 2022-08-12 17:47
@acocuzzo is it python 3.9?

**Comment by redvg** [comment] 2022-08-12 18:43
anyhow i could not make it work, i might provide a docker image for reproducing when i have time

for those struggling i fell back to `rele` which seem to be reliable alternate solution https://pypi.org/project/rele/

**Comment by acocuzzo** [comment] 2022-08-29 10:07
@redvg Yes, this was python 3.9. I'm glad you've found an alternate solution.

**Comment by acocuzzo** [comment] 2022-11-17 14:52
Closing this issue as we still don't have a reproduction.

**Closed by acocuzzo** 2022-11-17 14:52 UTC
Labels: api: pubsub, type: question
