### ISSUE TITLE
Pubsub requires grpcio package without compiled wheel

### ISSUE THREAD

**Issue by shaibt** [googleapis/python-pubsub#68] opened 2020-04-08 12:10 UTC
#### Environment details

Pubsub: google-cloud-pubsub 1.0.2

Python 3.6.3

Google App Engine flex python

#### Steps to reproduce

google-cloud-pubsub requires the grpcio package w/o locking a specific version.

On April 3rd a [new grpcio version](https://pypi.org/project/grpcio/1.28.1/#files) was released w/o a pre-compiled wheel - v 1.28.1

Since the new grpcio package release, GAE flex python deploys (using GAE default image) requiring google-cloud-pubsub are **timing out** because the grpcio package is being compiled during deploy time - which takes 8+ minutes.

google-cloud-pubsub should either lock to a specific grpcio version - one with a compiled wheel - or use a relevant pip flag to make sure it uses the latest compiled wheel available.

Doesn't make sense for GAE deploys to timeout because of this.
IssueTracker was opened here: https://issuetracker.google.com/issues/153468670

**Comment by plamut** [comment] 2020-04-08 13:24
@lidizheng Is making the Python wheel available something that can be fixed quickly?

**Comment by timc13** [comment] 2020-04-08 14:23
just to clarify - i don't believe this issue is restricted to `google-cloud-pubsub`.  I am experiencing the same behavior using `google-cloud-logging` It seems the underlying dependency should be fixed - https://github.com/googleapis/python-api-core

**Comment by lidizheng** [comment] 2020-04-08 17:18
@shaibt The Python community is moving from `manylinux1` to `manylinux2010` as their new standard for binaries. Unfortunately, `manylinux2010` won't be recognized by old `pip` until `>19.0.0`. gRPC Python's `v1.28.1` release migrated to `manylinux2010` to unblock gRPC Core from using more advanced feature.

Is upgrade `pip` in the toolchain an option for GAE team?

We had similar timeout issue with Cloud Function team, and after upgrading `pip` the rollout of `v1.28.1` is fine. If it is urgent, let's setup a meeting.

CC @gnossen

**Comment by jasonbrancazio** [comment] 2020-04-08 17:48
This is causing App Engine Flex builds on Cloud Build to time out as well

**Comment by gnossen** [comment] 2020-04-08 18:09
The announcement of the end of support for `manylinux1` is [here](https://groups.google.com/g/grpc-io/c/VdoTPMT5WwU/m/fMmXxFiBAwAJ). As @lidizheng pointed out, the ultimate solution is getting the version of pip used by appengine upgraded. We're contacting their team to make sure this happens. In the meantime, you can add `grpcio==1.27.2` to your `requirements.txt` to restore your build times.

**Comment by timc13** [comment] 2020-04-09 15:49
thanks @gnossen - where can we track this issue with the appengine team?

**Comment by gnossen** [comment] 2020-04-09 17:12
https://issuetracker.google.com/issues/153514651 appears to be the de facto tracking issue.

**Comment by busunkim96** [comment] 2020-06-23 04:08
The latest version of the App Engine Flex Python image now uses pip 20.0.2, so you should be able to remove any temporary pins on `grpcio`, `setuptools`, and `google-api-core`.

gcr.io/google-appengine/python

**Closed by busunkim96** 2020-06-23 04:08 UTC
Labels: api: pubsub, type: question

**Comment by jimwill3** [comment] 2020-07-02 17:46
I continue to get this message: "You are using pip version 10.0.1, however version 20.2b1 is available." This is in a new project. Anything I can do to troubleshoot? Still need to add a timeout to the build for grpcio to avoid timeouts.
thanks,
jim

**Comment by busunkim96** [comment] 2020-07-06 18:57
@jimwill3 Which image are you using? The pip version has been updated in the default Python image. If you are using a different image you will need to make the same change.

**Comment by jimwill3** [comment] 2020-07-06 19:57
the default one.  i have not altered the image. thanks,
jim

**Comment by busunkim96** [comment] 2020-07-06 20:17
Can you try re-deploying?

**Comment by jimwill3** [comment] 2020-07-06 21:58
I have been using  gcloud app deploy. 
last run (couple of minutes ago) displayed this:
Step #1: You are using pip version 10.0.1, however version 20.2b1 is available.
Step #1: You should consider upgrading via the 'pip install --upgrade pip' command

thanks,
jim

**Comment by busunkim96** [comment] 2020-07-06 22:00
@jimwill3 Just to confirm, you are using App Engine Flex?

**Comment by jasonbrancazio** [comment] 2020-07-07 00:12
@busunkim96 
The issue @jimwill3 is experiencing is not caused by the version of pip in the App Engine Flex image. Rather, the issue is with an outdated Cloud Build builder that builds App Engine Flex images. I've raised two issues on https://issuetracker.google.com/ but neither have been successfully resolved.

Here are minimal steps to reproduce the bug I've experienced, which reports the same message in step 1 that @jimwill3 sees. Note that in my case I'm adding tensorflow 2.1.1 is added to the requirements. This causes the build process to fail because the version of pip in the builder is out of date.

```
git clone https://github.com/GoogleCloudPlatform/python-docs-samples
cd ./python-docs-samples/appengine/standard_python37/hello_world/
echo "tensorflow==2.1.1" >> requirements.txt
echo "service: hello-world" > app.yaml
echo "runtime: python" >> app.yaml
echo "env: flex" >> app.yaml
echo "runtime_config:" >> app.yaml
echo "  python_version: 3.7" >> app.yaml
gcloud app deploy app.yaml --project <YOUR GCP PROJECT>
```

The configuration created by the echo commands above is a minimal, standard configuration for an App Engine Flex python deployment. Tensorflow 2.1.1 has been added to requirements.txt.

The build will start streaming logs to your terminal. Step #0 will succeed.

Then observe these lines in Step #1:
Step #1: Status: Downloaded newer image for gcr.io/cloud-builders/docker@sha256:461bb53c226048a2f5eabebe1d8b4367a02d3a484a8cc7455a21377702bbf4f6
Step #1: gcr.io/cloud-builders/docker@sha256:461bb53c226048a2f5eabebe1d8b4367a02d3a484a8cc7455a21377702bbf4f6

Note that gcr.io/cloud-builders/docker@sha256:461bb53c226048a2f5eabebe1d8b4367a02d3a484a8cc7455a21377702bbf4f6 is the builder being used in Step #1. This builder is woefully out of date.

Observe that the build FAILS in Step #1 with the following error:
Step #1: Collecting tensorflow==2.1.1 (from -r requirements.txt (line 2))
Step #1:   Could not find a version that satisfies the requirement tensorflow==2.1.1 (from -r requirements.txt (line 2)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)

To support my assertion above that the builder is woefully out of date:

Visit https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/docker@sha256:461bb53c226048a2f5eabebe1d8b4367a02d3a484a8cc7455a21377702bbf4f6/details?tab=info in a web browser

Observe that the Created Date is August 7, 2019.

Now visit
https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/docker?gcrImageListsize=30

Observe that the most recent version of the docker builder at the time of this writing (@sha256:9d616924efe7784bf3df3524bab889cdf81029541965712007169c3d0fafee5e)  was published on July 6, 2020 (today).

**Comment by busunkim96** [comment] 2020-07-07 00:52
@jasonbrancazio Could you link to the issues opened on issue tracker so I can ping the appropriate folks?

**Comment by jimwill3** [comment] 2020-07-07 12:13
yes. flex. saw the other comments from jasonbrancazio and experienced exact same tensorflow issues.
thanks,
Jim

________________________________

**Comment by jasonbrancazio** [comment] 2020-07-07 18:03
@busunkim96 they are private issues unfortunately. If you have the ability to search by title, search for "App Engine Flex python Cloud Build builder uses pip version 10.0.1, which doesn't see and thus won't install tensorflow 2.1"

**Comment by busunkim96** [comment] 2020-07-08 01:15
Ah I see. Internal issue 159878398 for any Googlers who are investigating.

**Comment by zero-master** [comment] 2020-09-05 02:26
Is there any update on this? Or are we supposed to continue using outdated version?

As of today I just tried deploying this app again and it blocks forever.

**Comment by lidizheng** [comment] 2020-09-08 17:17
@zero-master According to the internal thread, GAE & GCF has been updated. They installed Tensorflow 2.3.0 successfully, which is also `manylinux2010` standard binary. The blocker should be solved. Could you unpin `grpcio` and try again?
