### ISSUE TITLE
Infinite re-deliveries when using the pubsub emulator 

### ISSUE THREAD

**Issue by rettier** [googleapis/python-pubsub#30] opened 2020-02-10 22:22 UTC
We have come across an issue during development where long-running message callbacks would seem to never finish processing, when in reality the messages were redelivered indefinitely. I have distilled the problem down to the attached sample publisher and subscriber code. 

The behavior appears if the delay between publishing messages in a loop went above the 0.01 latency configured in the publisher's `BatchSettings`. If this was the case the subscriber would process the messages in order, and after processing the last message would start again somewhere and keep going forever. We were not able to reproduce the behavior with the actual pubsub system, but it begs the question if there is something wrong with our understanding of the pubsub system.

The attached sample code restricts the `ack_deadline_seconds` and `FlowControl.max_messages` in order to induce the behavior on a smaller, more debuggable, scale. If you comment out the sleep in `publisher.py:19` the messages are only processed once. I have also attached the debug log output of the subscriber (cut off, as it runs indefinitely).

As far as i understand it, if the ack deadline would be exceeded by the subscriber, it will renew the ack deadline until the `max_lease_duration` is reached. So in the case of slow running tasks, they should not cause any re-deliveries as long as the subscriber is running properly.

Is this a configuration/usage issue, a problem of the pub sub emulator or can a similar behavior also occur on the actual pub sub system?

Tested pub sub emulator version: 279.0.0 and 244.0.0
Client libraries:
* google-cloud-core==1.3.0
* google-cloud-pubsub==1.2.0
* googleapis-common-protos==1.6.0

`publisher.py`
```python
from time import sleep

from google.cloud import pubsub_v1
from google.cloud.exceptions import NotFound

project = "test"

pub = pubsub_v1.PublisherClient()
topic_path = pub.topic_path(project, "ackbug-test")

try:
    topic = pub.get_topic(topic_path)
except NotFound:
    topic = pub.create_topic(topic_path)

for x in range(30):
    print("Publish", x)

    # remove the sleep to avoid the bug
    sleep(0.01)

    pub.publish(topic_path, str(x).encode("ascii"))

```

`subscriber.py`
```python
import logging
from concurrent.futures.thread import ThreadPoolExecutor
from time import sleep

from google.api_core.exceptions import AlreadyExists
from google.cloud import pubsub_v1
from google.cloud.pubsub_v1.subscriber.scheduler import ThreadScheduler

logging.basicConfig(level=logging.DEBUG)


def callback(message):
    logging.info("received message id: {}".format(message.data.decode("ascii")))
    sleep(1)
    message.ack()


project = "test"
sub = pubsub_v1.SubscriberClient()
sub_path = sub.subscription_path(project, "ackbug-test-24")
topic_path = sub.topic_path(project, "ackbug-test")

try:
    sub.create_subscription(sub_path, topic_path, ack_deadline_seconds=5)
except AlreadyExists:
    pass

executor = ThreadPoolExecutor(max_workers=1)
scheduler = ThreadScheduler(executor)
flow_control = pubsub_v1.types.FlowControl(max_messages=10)

future = sub.subscribe(sub_path, callback, scheduler=scheduler, flow_control=flow_control)
future.result()
```

[subscriber.log.gz](https://github.com/googleapis/google-cloud-python/files/4183333/subscriber.log.gz)

**Comment by anguillanneuf** [comment] 2020-02-11 21:54
👋 @rettier Thank you for the question. I was able to reproduce the issue you described using your code. 

However, let me point out a few things - 

1. **The default and minimum `ack_deadline_seconds` in a subscription is 10 seconds** ([ref](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription)). After I updated your code to conform to the default,  *infinite* deliveries went away. However, I still observed that message 23-29 were *re*delivered, like 2-3 times. This tells me that the emulator probably does not enforce the field `ack_deadline_seconds` as the real Pub/Sub service does. 
```python
sub.create_subscription(sub_path, topic_path, ack_deadline_seconds=10)
```
2. **Under-provisioning your subscriber client is a bad idea.**  When you configure your subscriber's flow control settings to have a maximum number of 10 outstanding messages, your subscriber tries to hold on to as many as it can but not more than 10 messages while using as many threads as it has been provisioned to process message callbacks. Having fewer threads to process messages (in your code, 1) than the number of messages in the flow control setting (in your code, 10) caused some messages to expire. Message expiration, just like NACK'ing messages, will trigger both the emulator and the real service to  redeliver these messages. 
```python
executor = ThreadPoolExecutor(max_workers=10)
scheduler = ThreadScheduler(executor)
flow_control = pubsub_v1.types.FlowControl(max_messages=10)
```
After you make the above changes, redeliveries should go away.

**Comment by rettier** [comment] 2020-02-13 13:37
Thanks for the detailed explanation! I see that the main contributor are differences between the pub sub emulator and the real service. 

I have just one question regarding the second point. You mentioned that the messages may have expired past the ack deadline, because the subscriber was holding on some messages too long. Is the subscriber not renewing the ack deadline for those messages while it waits for them to be processed? It prints the following statement to the logfiles:
`DEBUG:google.cloud.pubsub_v1.subscriber._protocol.leaser:Renewing lease for 8 ack IDs.`

**Comment by anguillanneuf** [comment] 2020-02-13 23:28
Yes, the subscriber is designed to actively manage the leases of all messages that it holds, including messages scheduled for callbacks and those not scheduled for callbacks.

But undesirable race conditions can happen between an overloaded subscriber and the Pub/Sub server, and they can result in expired messages more easily. @plamut would you agree?

**Comment by plamut** [comment] 2020-02-14 08:40
The subscriber automatically lease-manages all messages that it receives, even those that are not scheduled for user callbacks yet due to `FlowControl` limits - up to `max_lease_duration`.

If, after delivery, the message processing would take a _really long_ time (2 hours, IIRC), a message could expire in the meantime, and the lease management thread would drop it. The backend would try to re-deliver the message, and sending a late ACK for such messages would have no effect (deadline missed).

 However, dropping expired message from the lease management would result in a warning in logs:
```
Dropping N items because they were leased too long
```
Does anything like that appear in the logs?

---

It's also worth mentioning that the most recent release (`v1.2.0`) modified a few things in the internal lease management. Does the same issue also occur in the previous release (`v1.1.0`) as well?

---

Since this behavior is reported when using an emulator, it cannot be excluded that it could be just the emulator behavior deviating from the actual system. I have not used the emulator myself,  though, thus I cannot say where the differences are in practice.

**Comment by anguillanneuf** [comment] 2020-02-14 21:24
@rettier Feel free to read on but this is getting into our client implementation details. I agree with @plamut that the emulator is causing this issue, not the client library, so I'm closing this bug. Sorry that our emulator is not perfect at the moment. 😞 

---
I compared two logs:
+ [`sub.log`]: 5 threads to process message callbacks, no infinite redeliveries
+ [`sub_bad_behavior.log`]: 1 thread to process message callbacks, infinite redeliveries

The main difference is that the good subscriber never logged out a line like ↓ while the bad subscriber did unendingly (when the message stream is paused). 

```
DEBUG   [2020-02-14 11:04:44,765] Thread-LeaseMaintainer : Renewing lease for 9 ack IDs.
``` 
https://github.com/googleapis/python-pubsub/blob/cc3093a2c0304259bc374bc2eeec9630e4a11a5e/google/cloud/pubsub_v1/subscriber/_protocol/leaser.py#L163-L177

Both did not log out `Dropping N items because they were leased too long`. 

[`sub.log`]: https://github.com/googleapis/python-pubsub/files/4206542/sub.log
[`sub_bad_behavior.log`]: https://github.com/googleapis/python-pubsub/files/4206544/sub_bad_behavior.log

**Closed by anguillanneuf** 2020-02-14 21:24 UTC
Labels: api: pubsub, type: question

**Comment by rettier** [comment] 2020-02-14 23:26
No thats perfectly fine! We are happy this is a emulator issue, which was caused by our specific development settings. We are currenrly running larger jobs in production and see no issues so far. Thank you for the detailed explanation!
