### ISSUE TITLE
 ImportError: cannot import name 'pubsub_v1' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by vskeid** [googleapis/python-pubsub#474] opened 2021-08-13 23:11 UTC
hi,
  Am trying to leverage Pub Sub in Google Cloud Functions as per the Environment Details below.  The code deployment is successful, but the function is not working since the pubsub library is not getting loaded.  The error is 
 ImportError: cannot import name 'pubsub_v1' from 'google.cloud' (unknown location)

#### Environment details

  - OS type and version: Google  Cloud Functions
  - Python version: `python --version`   Runtime : Python 3.9
  - pip version: `pip --version`
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`   google-cloud-pubsub==2.7.0

#### Steps to reproduce

  1.  Updates requirements.txt as per the below code example
  2. Invoke pubsub as per the example in main.py

#### Code example

```python
# requirements.txt
google-api-core==1.31.1
google-cloud-pubsub==2.7.0
#main.py
import os
import json
from google.cloud import pubsub_v1

def hello_world(request): 
    request_json = request.get_json()
    publisher = pubsub_v1.PublisherClient()
    topic_name = 'projects/{project_id}/topics/{topic}'.format(project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),topic='attendance-events')

    publisher.create_topic(name=topic_name)

    data = json.dumps(request_json).encode("utf-8")           
    future = publisher.publish(topic_name, data=data)
    future.result()

#### Stack trace
2021-08-13 17:52:54.953 ISTtestpublish Traceback (most recent call last): File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module> sys.exit(_cli()) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli app = create_app(target, source, signature_type) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 237, in create_app spec.loader.exec_module(source_module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/workspace/main.py", line 4, in <module> from google.cloud import pubsub_v1 ImportError: cannot import name 'pubsub_v1' from 'google.cloud' (unknown location)
`
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by plamut** [comment] 2021-08-19 07:40
@vskeid This is interesting, as I could not reproduce your error.

Is it possible that the script ran under in  _different_ Python environment that the one used to print the installed versions? I would double (or triple) check that first, as it seems like the most plausible explanation. We've actually had a few of those in the past.

**Comment by vskeid** [comment] 2021-08-19 17:49
Thanks for your reply. The issue is still there.   Please find the latest error stack trace

importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/workspace/main.py", line 3, in <module> from google.cloud import pubsub_v1 File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/pubsub_v1/__init__.py", line 19, in <module> from google.cloud.pubsub_v1 import subscriber File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/__init__.py", line 17, in <module> from google.cloud.pubsub_v1.subscriber.client import Client File **"/layers/google.python.pip/pip/lib/python3.9/**site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 26, in <module> from google.cloud.pubsub_v1.subscriber._protocol import streaming_pull_manager File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 35, in <module> import google.cloud.pubsub_v1.subscriber.message File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/message.py", line 20, in <module> **import pytz ModuleNotFoundError: No module named 'pytz'**

**Comment by hisashimurai** [comment] 2021-08-19 19:05
@vskeid Just I had the same thing yesterday and solved it with a workaround adding pytz to requirements.txt. It seems that the handling of pytz changed when the python client changed from v2.7.0 to v2.7.1. I think the cache had a temporary effect.

Now it seems to work fine without a workaround.

**Comment by plamut** [comment] 2021-08-20 08:51
@vskeid The missing `pytz` dependency is a different import error... or was the original error actually caused by that, but masking it?

The good news is that the `pytz` issue is known and has been fixed in yesterday's [v2.7.1](https://github.com/googleapis/python-pubsub/releases/tag/v2.7.1) release - could you please try it out and see if it fixes the problem?

The thing is that `pytz` was a transient dependency and was implicitly installed by the `google-api-core` dependency. When the latter recently dropped `pytz`, the libraries implictly depending on `pytz` also broke, unfortunately.

Anyhow, the Python Pub/Sub now dropped `pytz` altogether and should again work fine (in v2.7.1+). If that's not the case, please let me know to have another look, thanks!

**Comment by plamut** [comment] 2021-09-06 10:10
@vskeid Just checking, have you managed to solve the problem with the latest version of the Pub/Sub client? Is there anything else we can help with?

**Comment by plamut** [comment] 2021-09-16 09:14
Closing this, as it is believed that upgrading the client library to the latest version will fix the problem, and because there has been no new info for considerable amount of time.

@vskeid If the problem persists, please comment below and we can have another look.

**Closed by plamut** 2021-09-16 09:14 UTC
Labels: api: pubsub, type: question
