### ISSUE TITLE
module 'google.api_core' has no attribute 'gapic_v1'

### ISSUE THREAD

**Issue by ubaierbhat** [googleapis/python-pubsub#115] opened 2020-06-08 21:25 UTC
Since last week my DataFlow runs are failing because of this error. All I see in the logs is the following error

#### Stack trace
```python
AttributeError: module 'google.api_core' has no attribute 'gapic_v1'
at PublisherClient (/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py:245)
at <module> (/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py:75)
at <module> (/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/client.py:29)
at <module> (/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/__init__.py:17)
at <module> (/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/__init__.py:18)
at <module> (/usr/local/lib/python3.7/site-packages/etl/util.py:13)
at <module> (/usr/local/lib/python3.7/site-packages/etl/extract/m/a.py:10)
at <module> (/usr/local/lib/python3.7/site-packages/etl/extract/m/a.py:6)
at find_class (/usr/local/lib/python3.7/site-packages/dill/_dill.py:474)
at load (/usr/local/lib/python3.7/site-packages/dill/_dill.py:305)
at loads (/usr/local/lib/python3.7/site-packages/dill/_dill.py:317)
at loads (/usr/local/lib/python3.7/site-packages/apache_beam/internal/pickler.py:283)
at __init__ (/usr/local/lib/python3.7/site-packages/dataflow_worker/workercustomsources.py:144)
at get_work_items (/usr/local/lib/python3.7/site-packages/dataflow_worker/workitem.py:131)
at run (/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py:807)
```

#### Environment details
python 3.7
```
$ pip freeze | grep google
google-api-core==1.20.0
google-api-helper==0.3.1
google-api-python-client==1.9.2
google-apitools==0.5.31
google-auth==1.16.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-bigquery==1.24.0
google-cloud-bigtable==1.0.0
google-cloud-core==1.3.0
google-cloud-datastore==1.7.4
google-cloud-dlp==0.13.0
google-cloud-language==1.3.0
google-cloud-pubsub==1.0.2
google-cloud-spanner==1.13.0
google-cloud-videointelligence==1.13.0
google-cloud-vision==0.42.0
google-resumable-media==0.5.1
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3
```

**Comment by plamut** [comment] 2020-06-10 07:32
@ubaierbhat Could you please provide a bit more info, e.g. versions installed etc.? That would make diagnosing the issue easier, thanks!

(you can take GitHub issue bug report template as a guidance)

**Comment by ubaierbhat** [comment] 2020-06-10 09:25
@plamut I have updated the description. the builds started failing since 5th June. The versions were set dynamically so I can't find out which versions were run before 5th.

**Comment by ubaierbhat** [comment] 2020-06-12 04:07
@plamut regression in `google-api-core` is causing this problem    https://github.com/googleapis/python-api-core/issues/47

This issue can be moved `google-api-python-client` (as latest version 1.9.* requires `google-api-core >= 1.18.0`)

the temporary solution is to pin  google-api-python-client to an older version
```
'google-api-core==1.17.0',
'google-api-python-client==1.8.4'
```

**Comment by plamut** [comment] 2020-06-12 11:00
@ubaierbhat Thanks for additional research, I only found the time to come back at this today.

It indeed seems like an external issue, but since a workaround exists, I'll classify it as P2.

By the way - `google-api-core` 1.17.0 suffers from [another regression](https://github.com/googleapis/python-pubsub/issues/93) that breaks the streaming pull, thus the users that use that feature should instead temporarily pin `google-api-core` to an even older version, e.g. `1.16.0`.

**Comment by meredithslota** [comment] 2020-08-14 19:57
The root cause was fixed in https://github.com/googleapis/python-api-core/issues/47 so it should be (famous last words) safe to unpin versions as per @busunkim96's comment on June 18th: https://github.com/googleapis/python-api-core/issues/47#issuecomment-646374196

@ubaierbhat Can you try bumping the version for `google-api-core` and seeing if that fixes the issue?

**Comment by bayesfactor** [comment] 2020-09-18 20:13
I had to downgrade to 1.16.0 to resolve the import error

**Comment by meredithslota** [comment] 2021-02-02 20:14
Removing the "external" label since the external issue is fixed.

**Comment by plamut** [comment] 2021-02-09 08:48
@ubaierbhat @bayesfactor The external issue has been fixed, can any of you two confirm that by upgrading the dependencies to ther latest versions indeed fixes the issue?

Thanks!

**Comment by meredithslota** [comment] 2021-02-17 19:16
I'm going to go ahead and close this for now, but please feel free to reopen if the fix does not resolve your issue!

**Closed by meredithslota** 2021-02-17 19:16 UTC
Labels: :rotating_light:, api: pubsub, priority: p2, type: bug

**Comment by ubaierbhat** [comment] 2021-02-17 19:21
@meredithslota thanks and sorry, wasn't able to test because of busy schedule. I will test and report if the issue still exists (hopefully won't need to 🤞 )
