### ISSUE TITLE
Generator already executing

### ISSUE THREAD

**Issue by rafa-acioly** [googleapis/python-pubsub#160] opened 2020-07-16 13:20 UTC
#### Environment details

  - Python version: 3.7.0
  - `google-cloud-pubsub` version: 1.7.0

#### Code example

```python

class Processor:

    def process(self, message):
        print("message received")


class Consumer:

    def __init__(self):
        subscriber = pubsub_v1.SubscriberClient()
        subscription_path = subscriber.subscription_path(
            self.project_name, self.scope
        )
        
        processor = Processor()
        self.subscriber = subscriber.subscribe(
            subscription_path,
            callback=processor.process,
            flow_control=pubsub_v1.types.FlowControl(
                max_messages=100
            )
        )

    def sleep(self):
        time.sleep(60)

consumer = Consumer()
while True:
     consumer.sleep()
```

#### Stack trace
```
[2020-07-16 12:46:58,978] [18] [ERROR] grpc._channel:203 - Exception iterating requests!
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/grpc/_channel.py", line 195, in consume_request_iterator
    request = next(request_iterator)
ValueError: generator already executing
[2020-07-16 12:46:58,982] [18] [INFO] google.api_core.bidi:676 - Thread-ConsumeBidirectionalStream exiting
[2020-07-16 12:47:05,717] [18] [INFO] google.cloud.pubsub_v1.subscriber._protocol.heartbeater:44 - Thread-Heartbeater exiting.
[2020-07-16 12:47:06,084] [18] [INFO] google.cloud.pubsub_v1.subscriber._protocol.leaser:189 - Thread-LeaseMaintainer exiting.
```

#### Dependencies

```
google-cloud-pubsub==1.7.0
google-cloud-core==1.3.0
```

**Comment by plamut** [comment] 2020-07-16 17:43
@rafa-acioly Since this sounds like a bug, could you please post the versions of other packages installed in the environment? Especially `google-api-core` and `grpcio` versions.

is the issue consistently reproducible or does it only happen sporadically?

**Comment by rafa-acioly** [comment] 2020-07-16 17:47
@plamut here's the package version for another services;

```
grpcio==1.27.2
google-cloud-pubsub==1.7.0
google-cloud-storage==1.29.0
google-cloud-bigquery==1.25.0
google-cloud-core==1.3.0
google-api-core==1.16.0
```

The issue is consistent, every time i start my consumer after a few minutes this errors shows up

**Comment by plamut** [comment] 2020-07-17 09:18
@rafa-acioly Unfortunately, I was not able to reproduce the issue locally, even if tweaking the posted example (I added `message.ack()` to `Processor.process()`, for instance).

Since a few dependencies are not up to date, could you perhaps try upgrading them and see if the issue still persists? E.g.:
```py
google-api-core==1.21.0
grpcio==1.30.0
```

If updating dependencies still does not help, could you set logging level to DEBUG to see if there's some extra info that we can use to narrow down the cause?

**Comment by plamut** [comment] 2020-07-24 13:25
@rafa-acioly Did upgrading dependency work, or does the issue still persist?

**Comment by rafa-acioly** [comment] 2020-07-27 20:31
@plamut in fact i've "downgraded" the dependencies, for some reason the messages weren't being consumed and now it works fine :(

This are the dependencies
```
grpcio==1.27.2
google-cloud-pubsub==1.4.3
google-cloud-storage==1.14.0
google-cloud-bigquery==1.23.0
google-cloud-core==1.1.0
```

I'll close this issue because i can't give more attention to this "problem" right now, ok?

**Comment by plamut** [comment] 2020-07-28 04:16
@rafa-acioly If you had to downgrade the dependencies in order to fix the issue, it means that the bug still exists with some combination of dependencies and user code, thus I'll keep it open for better visibility.

Feel free to re-visit it at some later point if/when you have more info (my reproduction attempt was not successful, unfortunately), but even if you can't give more attention to it, it's also fine.

**Comment by sandrochuber** [comment] 2020-09-03 08:08
I'm also experiencing this behavior.

For me this happened with these versions:
```
google-api-python-client==1.7.11
google-api-core==1.19.0
google-auth==1.11.2
google-cloud-firestore==1.6.2
google-cloud-iam==0.2.1
google-cloud-pubsub==1.2.0
google-cloud-storage==1.26.0
```

It seems to work again after bumping all to the most recent version:
```
google-api-python-client==1.11.0
google-api-core==1.22.1
google-auth==1.21.0
google-cloud-firestore==1.9.0
google-cloud-iam==2.0.0
google-cloud-pubsub==1.7.0
google-cloud-storage==1.31.0
```

Probably not all packages are relevant for fixing this.

**Comment by randolfo75** [comment] 2020-10-04 20:01
Same here, after update all packages problem solved, I still receive some errors, but now the subscription remains working.

**Comment by plamut** [comment] 2021-01-07 09:52
Since it was reported that upgrading the packages to more recent versions fixed the issue, I'm closing this.

However, should anyone manage to reproduce the issue again even with the up-to-date versions, please drop a note here and we can take another look.

**Closed by plamut** 2021-01-07 09:52 UTC
Labels: api: pubsub, needs more info, priority: p2, type: bug
