### ISSUE TITLE
PubSub crashes on timeout and can't recover (google.api_core error)

### ISSUE THREAD

**Issue by szeitlin** [googleapis/python-pubsub#176] opened 2020-08-13 18:12 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

`I'm going to do both, thanks.` 

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-python/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-python

`Done and done.` 

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

2. OS type and version
`Works on MacOS and debian linux locally and in GCB, does not work in debian linux on GKE`

3. Python version and virtual environment information: 

`3.7.6`

4. google-cloud-<service> version:  

`google-api-core==1.22.0
google-auth==1.20.1
google-cloud-pubsub==1.7.0
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3
grpcio==1.31.0
`

#### Steps to reproduce

  1. Run python code locally in MacOS, confirm that it works and tests pass. 
  2. Run python code locally in docker container, confirm that it works and tests pass.
  3. Run python code on GCB as part of CICD process, confirm that tests pass and build succeeds. 
  4. Deploy python code in docker container on GKE, watch it fail! 
  5. Shell into the kubernetes pod, run python code there, watch it fail!

#### Code example

```python
    def async_pull(self) -> None:
        """
        Asynchronously streams messages from pubsub and calls the callback() on them
        """
        streaming_pull_future = self.subscriber.subscribe(
            self.subscription_path, callback=self.callback
        )

        log.info(f"Listening for messages on {self.subscription_path}...")

        with self.subscriber:
            try:
                streaming_pull_future.result(timeout=self.pubsub_timeout)

            except TimeoutError:  
                streaming_pull_future.cancel()
                logging.error(
                    f"Streaming_pull_future timed out while listening for messages on {self.subscription_path}"
                )
```

#### Stack trace
```
08-13 17:32:27 __main__: INFO Listening for messages on subscriber...
ERROR:root:Streaming_pull_future timed out while listening for messages on subscriber
08-13 17:32:32 __main__: INFO Listening for messages on subscriber...
ERROR:google.api_core.bidi:Thread-ConsumeBidirectionalStream caught unexpected exception Cannot invoke RPC: Channel closed! and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/bidi.py", line 637, in _thread_main
    self._bidi_rpc.open()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/bidi.py", line 280, in open
    call = self._start_rpc(iter(request_generator), metadata=self._rpc_metadata)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 1185, in streaming_pull
    requests, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 144, in error_remapped_callable
    result = callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 1089, in __call__
    operationses, event_handler, self._context)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 1183, in create
    operationses_and_tags, context)
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 476, in grpc._cython.cygrpc.Channel.integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 294, in grpc._cython.cygrpc._integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 258, in grpc._cython.cygrpc._call
ValueError: Cannot invoke RPC: Channel closed!

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by meredithslota** [comment] 2020-08-18 17:38
Thank you for the detailed report. @pradn or @plamut Can you take a look?

**Comment by plamut** [comment] 2020-08-18 18:04
I might have time to look at this in a few days or early next week (currently finalizing two other pretty sizeable tasks).

**Comment by szeitlin** [comment] 2020-08-19 19:59
I think there may be something wrong with the context manager setup, because I also see this error with synchronous pull when I do `with subscriber:` but I don't see it if I remove that.

**Comment by plamut** [comment] 2020-08-24 15:19
@szeitlin On the surface it seems that there is some sort of a race condition when the streaming pull future is shut down by a timeout and the the message stream in the background sometimes does not get shut down cleanly.

I am curious, thought, what is the use case for passing a timeout to the future? Is to to terminate the stream after some fixed time period?
```py
streaming_pull_future.result(timeout=self.pubsub_timeout)
``` 

Asking because streaming pull is essentially an infinite process that only terminates if a future is explicitly canceled or if an irrecoverable stream error occurs. In fact, `streaming_pull_future.result()` is designed to block indefinitely, at least until the user call explicitly invokes its `cancel()` method.

**Comment by szeitlin** [comment] 2020-08-24 17:30
@plamut That sort of makes sense... I think we were worried about streams not getting terminated if an error occurs. Also we were following the example verbatim:

```with subscriber:
    try:
        # When `timeout` is not set, result() will block indefinitely,
        # unless an exception is encountered first.
        streaming_pull_future.result(timeout=timeout)
    except TimeoutError:
        streaming_pull_future.cancel()
```

from the docs here: https://cloud.google.com/pubsub/docs/pull#python

If we can safely use it without the timeout, I can just remove it, but I don't want to run up a huge bill or cause everything to hang if we ended up with a bunch of unused streams or dangling threads.

**Comment by plamut** [comment] 2020-08-25 09:25
With some trial and error I was able to occasionally reproduce the reported behavior, sometimes shutting down the stream after a timeout does not work cleanly.

<details>
  <summary>Two different error tracebacks ↓</summary>

**Error:**
```
ERROR    [2020-08-25 10:48:02,020] Thread-ConsumeBidirectionalStream [google.api_core.bidi] [bidi.py:673][_thread_main] Thread-ConsumeBidirectionalStream caught unexpected exception cannot schedule new futures afterinterpreter shutdown and will exit.
Traceback (most recent call last):
  File "/home/peter/workspace/python-api-core/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 637, in _on_response
    self._maybe_release_messages()
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 334, in _maybe_release_messages
    self._schedule_message_on_hold(msg)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 365, in _schedule_message_on_hold
    self._scheduler.schedule(self._callback, msg)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/scheduler.py", line 111, in schedule
    self._executor.submit(callback, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 153, in submit
    raise RuntimeError('cannot schedule new futures after'
RuntimeError: cannot schedule new futures afterinterpreter shutdown
```

**Another manifestation:**
```
ERROR    [2020-08-25 10:50:39,583] Thread-CallbackRequestDispatcher  [google.cloud.pubsub_v1.subscriber._protocol.helper_threads] [helper_threads.py:110][__call__] Error in queue callback worker: Cannot invoke RPC on closed channel!
Traceback (most recent call last):
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py", line 108, in __call__
    self._callback(items)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 119, in dispatch_callback
    self.ack(batched_commands.pop(requests.AckRequest))
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 146, in ack
    self._manager.send(request)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 405, in send
    self._send_unary_request(request)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 377, in _send_unary_request
    subscription=self._subscription, ack_ids=list(request.ack_ids)
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/home/peter/workspace/python-pubsub/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 1022, in acknowledge
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/peter/workspace/python-api-core/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/peter/workspace/python-api-core/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/peter/workspace/python-api-core/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/peter/workspace/python-api-core/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/peter/workspace/python-api-core/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/peter/workspace/python-pubsub/env/3.7/lib/python3.7/site-packages/grpc/_channel.py", line 825, in __call__
    wait_for_ready, compression)
  File "/home/peter/workspace/python-pubsub/env/3.7/lib/python3.7/site-packages/grpc/_channel.py", line 812, in _blocking
    ),), self._context)
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 353, in grpc._cython.cygrpc._segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 357, in grpc._cython.cygrpc._segregated_call
ValueError: Cannot invoke RPC on closed channel!
```
</details>

@anguillanneuf 
Do you remember if we perhaps need to adjust the [official sample](https://cloud.google.com/pubsub/docs/pull#asynchronous-pull)? Is using a timeout to terminate the streaming pull after a fixed time period an officially suggested pattern in other languages' clients, too?

Also asking because I noticed that the streaming pull gets shut down on timeout fine even without the `.cancel()` call in the `except` block (at least when bad race conditions don't kick in).

> If we can safely use it without the timeout, I can just remove it, but I don't want to run up a huge bill or cause everything to hang if we ended up with a bunch of unused streams or dangling threads.

It should probably be fine, as the [billing docs](https://cloud.google.com/pubsub/pricing#message_ingestion_and_delivery) suggest that the cost depend on the value of data transmitted. If the RPC channel is irrecoverably closed, no messages get delivered - but I'll double check, just in case.

**Comment by anguillanneuf** [comment] 2020-08-25 17:22
@plamut Yes, we have the official Java [sample](https://cloud.google.com/pubsub/docs/pull#java) following the same pattern.

Previous iterations of the official Python samples don't make use of `streaming_pull_future` or the try..except block. It was simply `subscriber.subscribe()`. We altered them in favor of using a context manager. @pradn 

Will the behavior change if we also wrap `streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)` in the context manager?

**Comment by plamut** [comment] 2020-08-27 18:21
@szeitlin Got confirmation that billing shouldn't be an issue, as only the message data actually transmitted gets billed. Having an idle stream is free, and modACK requests are not billed (the library does that in the background to extend the ACK deadlines of leased messages).

Regarding the pricing, usually the main gotcha is not acknowledging messages and when they eventually get re-delivered, the user gets billed for the data that has already been sent to them before.

**Comment by szeitlin** [comment] 2020-08-28 00:22
> @szeitlin Got confirmation that billing shouldn't be an issue, as only the message data actually transmitted gets billed. Having an idle stream is free, and modACK requests are not billed (the library does that in the background to extend the ACK deadlines of leased messages).
> 
> Regarding the pricing, usually the main gotcha is not acknowledging messages and when they eventually get re-delivered, the user gets billed for the data that has already been sent to them before.

Thanks, that's good to know.

**Comment by meredithslota** [comment] 2020-10-15 17:42
It seems like this is resolved based on usage guidance - I'm going to go ahead and close this but please feel free to reopen if your issue isn't solved.

**Closed by meredithslota** 2020-10-15 17:42 UTC
Labels: api: pubsub, priority: p2, type: bug

**Comment by scottw** [comment] 2021-05-18 22:52
This problem still exists ([the docs](https://cloud.google.com/pubsub/docs/pull#streamingpull), but you can avoid the grpc thread problems if you don't use a context manager for the subscriber.

**Comment by plamut** [comment] 2021-05-19 07:44
The very latest release ([v2.5.0](https://github.com/googleapis/python-pubsub/releases/tag/v2.5.0)) contains a fix that avoids a few background errors that can sometimes happen on shutdown due to race conditions.

As for the linked sample, the `future.cancel()` call is non-blocking by default, and if the execution flow exits the context manager, the latter closes the channel, but that can cause an error when the shutdown is still in progress in the background (e.g. the client tries to automatically NACK any internally queued messages).

@anguillanneuf It appears that the sample might be outdated - if the subscriber context manager is used, the code inside the `with` block should wait until the shutdown is complete before leaving the block. Using a blocking shutdown and blocking on `future.result()` is one way to do it.

**Comment by hrossow** [comment] 2021-05-28 11:39
@plamut,

I can relate  to this strange behaviour, while developing a application that interfaces pub_sub using 2.5.0 (from google.cloud import pubsub_v1) since streaming_pull_future.cancel() is non blocking it raises the RPC call exception.

Made some runs and simply using time.sleep() prevents the error from happening, it's not beautfull code at all, but... it's a workarround. Is it possible to pass a param to future.cancel in order to turn it in a blocking operation?
`with subscriber:
    try:
        streaming_pull_future.result(timeout=timeout)
    except TimeoutError:
        streaming_pull_future.cancel()
        time.sleep(5)
`

**Comment by plamut** [comment] 2021-05-28 15:35
@hrossow Adding a new parameter to the `cancel()` method to control whether or not to block is not an option, unfortunately.  It was actually added not that long ago, but that [broke](https://github.com/googleapis/python-pubsub/issues/318) a related library Pub/Sub Lite, and had to be refactored.

As of version [v2.4.1](https://github.com/googleapis/python-pubsub/releases/tag/2.4.1), the `cancel()` is non-blocking (as it should be). It just triggers the shutdown of the background message stream and returns immediately. To actually block until the shutdown completes in the background, `future.result()` should be called.

```py
with subscriber:
    try:
        streaming_pull_future.result(timeout=timeout)
    except TimeoutError:
        streaming_pull_future.cancel()  # triggers the shutdown, but does not block
        streaming_pull_future.result()  # block until shutdown is complete
```

It's also worth mentioning that by default, `future.result()` will not wait for any currently executing message callbacks to finish running. If one also needs to ensure that all callbacks first finish, the `await_callbacks_on_shutdown` parameter must be set to `True` when calling [subscriber.subscribe()](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.subscribe) (also mentioned in the docs).

Does this help with your issue?

---
@anguillanneuf I see that the base streaming pull [sample](https://cloud.google.com/pubsub/docs/samples/pubsub-subscriber-async-pull) has not been updated yet, and if users use it as-is, they will likely experience the error @hrossow mentioned. Do we have ETA for that? I'm also willing to help, if needed.

has recently been made non-blocking method  After cancelling the streaming pull

**Comment by hrossow** [comment] 2021-05-28 17:07
@plamut,

This is perfect! I believe that this is the same as implementing inside a while.

**Comment by plamut** [comment] 2021-05-28 20:49
@hrossow I'm glad that it helped you!

As for the `while` loop, it's doing unnecessary work while it could simply be blocking. Every call to [cancel()](https://github.com/googleapis/python-pubsub/blob/e907f6e05f59f64a3b08df3304e92ec960997be6/google/cloud/pubsub_v1/subscriber/futures.py#L46-L53) invokes `close()` on the streaming pull manager, which creates a [new thread](https://github.com/googleapis/python-pubsub/blob/e907f6e05f59f64a3b08df3304e92ec960997be6/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L569-L575).

It's true that those additional threads will just block when trying to acquire the `self._closing` lock in `_shutdown()`, and then return immediately when the first shutdown thread is done, but it's still a waste creating them in the first place. I would just stick to a single `cancel()` called followed by a blocking `result()`.

**Comment by tracy-ash** [comment] 2024-02-21 22:18
> @anguillanneuf I see that the base streaming pull [sample](https://cloud.google.com/pubsub/docs/samples/pubsub-subscriber-async-pull) has not been updated yet, and if users use it as-is, they will likely experience the error @hrossow mentioned. Do we have ETA for that? I'm also willing to help, if needed.

I am running into this problem, and the docs are still not updated. I cannot find `await_callbacks_on_shutdown` anywhere.  I'll try setting this to `True` to see if it fixes my problem.
