### ISSUE TITLE
Intermittent error message AuthMetadataPluginCallback : ValueError: None could not be converted to unicode

### ISSUE THREAD

**Issue by nguaman** [googleapis/python-pubsub#737] opened 2022-07-13 17:54 UTC
Hello,

I have an error that appears intermittently, there may be days without the error appearing or there are times when the error is present throughout the day.

I managed to reproduce the error once, but after running the code more than 30 times.

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: 3.9
  - pip version: 22.1.2
  - `google-cloud-pubsub` version: 2.13.0

#### Steps to reproduce

  1. Create a Topic
  2. Create a subscription.
  3. Publish dummy data to this Topic.
  2. Execute the code example many times with new/same dummy data each time. (JSON)

#### Code example

```
.env
EXPORT GOOGLE_APPLICATION_CREDENTIALS=./credentials.json
```

```python
import json
from dotenv import load_dotenv
import os
from google.cloud import pubsub_v1
import logging
from pprint import pprint 


class GoogleSub:
	def __init__(self):

		load_dotenv()

		self.project_id = os.environ["PROJECT_ID"]
		self.subscriber_name = "sub_terms_google"

		# google pub/sub : subscriber
		self.subscriber = pubsub_v1.SubscriberClient()
		self.subscription_path = (
			f"projects/{self.project_id}/subscriptions/{self.subscriber_name}"
		)

		self.logger = logging.getLogger(__name__)


	def callback(self, message):

		data = json.loads(message.data)

		message.ack()

	def run(self):

		streaming_pull_future = self.subscriber.subscribe(
			self.subscription_path, callback=self.callback
		)

		with self.subscriber:
			streaming_pull_future.result()


if __name__ == "__main__":

	GoogleSub().run()

```

#### Stack trace
```
2022-07-13 18:00:17 ERROR    AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f43bda11730>" raised exception!
Traceback (most recent call last):
  File "/home/nguaman/.local/lib/python3.9/site-packages/grpc/_plugin_wrapping.py", line 89, in __call__
    self._metadata_plugin(
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 101, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 87, in _get_authorization_headers
    self._credentials.before_request(
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/credentials.py", line 134, in before_request
    self.apply(headers)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/credentials.py", line 110, in apply
    _helpers.from_bytes(token or self.token)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/_helpers.py", line 126, in from_bytes
    raise ValueError("{0!r} could not be converted to unicode".format(value))
ValueError: None could not be converted to unicode
```

Thanks!

**Comment by acocuzzo** [comment] 2022-07-14 20:08
@nguaman This looks like a authentication error to me, 

Can you check the roles on your service account?

gcloud asset search-all-iam-policies --query="policy:{your-service-account-id}@{your-project}.iam.gserviceaccount.com"

**Comment by acocuzzo** [comment] 2022-07-23 19:22
@nguaman I have not been able to reproduce the error. Was there any timing pattern to the errors? Is it usually on start up, or after been connected for ~35 min?

**Comment by nguaman** [comment] 2022-07-24 13:37
> @nguaman I have not been able to reproduce the error. Was there any timing pattern to the errors? Is it usually on start up, or after been connected for ~35 min?

After several attempts, I managed to get some metrics.

- I get the error when I have a subscriber and a publisher in the same code. 
- Commonly, this error occurs after 5 minutes of the subscriber listening for requests.

In the follow issue, the error is also commented.

https://github.com/googleapis/google-auth-library-python/issues/927

**Comment by z3z1ma** [comment] 2022-07-25 04:06
I get the same error using BigQuery Storage Write API which I believe is using pub/sub in the internals. 

There error plus the originating method can be discerned from the below logs. Note these are exposed through a logging interface overlaying a subprocess but the google interface log information can still be easily seen. 

```
2022-07-25T03:04:20.962922Z [info     ] time=2022-07-24 20:04:20 name=grpc._plugin_wrapping level=ERROR message=AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x11f971cd0>" raised exception! cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.962972Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.963045Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/grpc/_plugin_wrapping.py", line 89, in __call__ cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.963093Z [info     ]     self._metadata_plugin(     cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.963141Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 101, in __call__ cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.963190Z [info     ]     callback(self._get_authorization_headers(context), None) cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.963237Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 87, in _get_authorization_headers cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965300Z [info     ]     self._credentials.before_request( cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965352Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/google/auth/credentials.py", line 134, in before_request cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965400Z [info     ]     self.apply(headers)        cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965448Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/google/auth/credentials.py", line 110, in apply cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965498Z [info     ]     _helpers.from_bytes(token or self.token) cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965546Z [info     ]   File "/Users/alexanderbutler/Documents/harness/analytics-pipelines/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/google/auth/_helpers.py", line 130, in from_bytes cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965844Z [info     ]     raise ValueError("{0!r} could not be converted to unicode".format(value)) cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
2022-07-25T03:04:20.965893Z [info     ] ValueError: None could not be converted to unicode cmd_type=elb consumer=True name=target-bigquery producer=False stdio=stderr string_id=target-bigquery
```

Here is the offending function
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/41213451/180696552-411414f4-ba54-471a-b7c5-f5f47a20a0ab.png">

And here is the caller
<img width="678" alt="image" src="https://user-images.githubusercontent.com/41213451/180696712-853ced7f-8319-43f2-a8f0-534fee83062d.png">

We can see token is an optional kwarg.

So lets go up one more trace
<img width="668" alt="image" src="https://user-images.githubusercontent.com/41213451/180696941-fe3224b0-91eb-42aa-bc66-3090d4724016.png">

And there is the issue. ☝️

**Comment by z3z1ma** [comment] 2022-07-25 04:12
Somehow the `credential` object has None set for token. 
This happens to me after quite a long time connected a grpc instance

**Comment by nguaman** [comment] 2022-08-03 07:46
Same Issue : https://github.com/grpc/grpc/issues/30460

**Comment by nguaman** [comment] 2023-01-11 21:15
Any news about this ?

**Comment by acocuzzo** [comment] 2023-02-14 17:16
Closing as this seems to be a duplicate issue of: https://github.com/googleapis/google-auth-library-python/issues/927

**Closed by acocuzzo** 2023-02-14 17:16 UTC
Labels: api: pubsub, type: question
